services:
  db:
    image: postgres
    container_name: database
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER:  rdelicad
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../customer:/tmp/data/customer
      - ../item:/tmp/data/item
      #- ~/$(USER)/customer:/tmp/data/customer
      #- ~/${USER}/item:/tmp/data/item
    networks:
      - net_postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - "8080:80"
    networks:
      - net_postgres

volumes:
  postgres_data:

networks:
  net_postgres:
    name: postnet